# Generated by Django 3.2.4 on 2021-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('bba', 'BBA'), ('bca', 'BCA'), ('mba', 'MBA'), ('mca', 'MCA'), ('cse', 'CSE'), ('it', 'IT'), ('mech', 'MECH'), ('ele', 'ELE')], default='B.Tech', max_length=6),
        ),
    ]
