# Generated by Django 3.2.4 on 2021-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_portal', '0005_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_image'),
        ),
    ]
