# Generated by Django 3.2.4 on 2021-06-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_portal', '0007_alter_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
